### ISSUE TITLE
Have multiple referred friend before completing the "Refer a friend" activity

### ISSUE THREAD

**Issue by aurelticot** [verida/incentivized-testnet-webapp#133]
```[tasklist]
### Tasks
- [ ] Define a constant for the number of referrals to acheive
- [ ] Check the number of referral confirmation message received to complete
- [ ] Update the UI to display the information (number of referrals received, number to go, etc.)
```
