### ISSUE TITLE
Disable Terms & Conditions

### ISSUE THREAD

**Issue by aurelticot** [verida/incentivized-testnet-webapp#47]
For launch, disable the required Terms & Conditions agreement, but keep the implement for when we will enable it again.
```[tasklist]
### Tasks
- [x] Disable Terms & Conditions
- [x] Hide Terms & Conditions link in footer
- [x] Add message "Eligibility conditions and terms of use will apply"
```
