### ISSUE TITLE
Optimise Sentry error reporting

### ISSUE THREAD

**Issue by aurelticot** [verida/incentivized-testnet-webapp#55]
```[tasklist]
### Tasks
- [x] Ignore browser extensions
- [x] Allow list urls
- [x] Ignore already identified Verida SDK issues, for now
- [x] Ignore known ResizeObserver issue
```

Check https://nesin.io/blog/filter-sentry-errors
